language: python
python:
- 3.6
- 3.5
- 3.4
- 2.7
install: pip install -U tox-travis
before_script: flake8 python_chess tests
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: zacharyrsmith
  password:
    secure: NZlJbeyNYn/Qx+Q1gcYauqI6mNBNuN0a2W8DAj+NdfWBVxuIMU7tgu6OB5SinJaNgOX7SkYPnBF/DK+Dr9cVTxwuzHofcVf/QoEO5XHbtzOjmZ4utpVoTHqkW4Cvg577orasfwpaQO0vSVawke5Oz2rnGWjsNQgqDc/AE3y0Q+auWRwC9cAnBWZPdZo8Vj/MYqikg7j7VwZmNTl5rmk9xoip58YOtDvFUdQ/qmlPKxMM0MhpZPhf8Lv37PyZ3lB5KraY99oDZwJ+XBcL+fluKaWFXx2CW3HKCKI8k1eUr2ZulT9O0feLeko0gmart6+uaRHeBXMwXC68rs6QKrO/0douAwX6v5UkS4Y756Xa9XMcJdpLIM+OeQeJaoGHqNF92Q0zG5NfPQGPyQvke2meRx/wrS87dafoY2dDnbBbKvY2Rp8CfrZGBAh9LNQAiO8UMdzX3w/YwStZEOySrOLZQqxFYLzf2j4CpNnT6GlZlVj0utuXHhUmxfht/q4Mn7A+oz8t6RjZF5s1PD/X42Gqf9nANuOu+zW8oXnlBerZeHgXfnWrzjoA0sl+qj1sbG2/Lbmx0I8BW6qjWkxZ8s+rbP1c3YwpCLjiXpuuM6erAdZivveRMq37U0/4ATovsmaGBBYdP+7F8nu6zPJqkZnFeQE1ZaCbk1pNfuctv9dLMIw=
  on:
    tags: true
    repo: zacharyrsmith/python_chess
    python: 3.6
